import type { Metadata } from 'next'
import HomeClient from './HomeClient'
import { SearchActionSchema } from './components'

export const metadata: Metadata = {
  title: 'RandomKeygen - Free Secure Password & Key Generator',
  description: 'Professional keygen toolkit: generate secure passwords, API keys, UUIDs, JWT secrets, encryption keys, and more. Free, open-source, runs entirely in your browser.',
  keywords: ['keygen', 'password generator', 'random key generator', 'API key', 'UUID generator', 'JWT secret', 'encryption key', 'secure password', 'key generation'],
  openGraph: {
    title: 'RandomKeygen - Free Secure Password & Key Generator',
    description: 'Generate cryptographically secure passwords, API keys, UUIDs, and more. Free and runs entirely in your browser.',
    url: 'https://randomkeygen.com',
    siteName: 'RandomKeygen',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'RandomKeygen - Free Secure Password & Key Generator',
    description: 'Generate cryptographically secure passwords, API keys, UUIDs, and more.',
  },
  alternates: {
    canonical: 'https://randomkeygen.com',
  },
}

// JSON-LD structured data for SEO
const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'RandomKeygen',
  alternateName: 'Random Key Generator',
  description: 'Professional keygen toolkit: generate cryptographically secure passwords, API keys, UUIDs, JWT secrets, encryption keys, and more. Free, open-source, runs entirely in your browser.',
  url: 'https://randomkeygen.com',
  applicationCategory: 'SecurityApplication',
  applicationSubCategory: 'Password Generator',
  operatingSystem: 'Any',
  browserRequirements: 'Requires JavaScript',
  softwareVersion: '2.0',
  datePublished: '2020-01-01',
  dateModified: '2026-03-27',
  publisher: {
    '@type': 'Organization',
    name: 'RandomKeygen',
    url: 'https://randomkeygen.com',
  },
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
    availability: 'https://schema.org/InStock',
  },
  featureList: [
    'Secure password generation with customizable length and complexity',
    'Pronounceable and memorable password generation',
    'Professional API key generation for AWS, GitHub, Stripe formats',
    'UUID v4 generation for unique identifiers',
    'JWT secret key generation with cryptographic security',
    'AES, RSA, and HMAC encryption key generation',
    'TOTP authenticator secret generation',
    'Bulk password generation for teams',
    'WiFi WPA2/WPA3 password generation',
    'Framework-specific keys (Django, Laravel, Flask)',
    'Client-side only processing - no data transmitted',
    'Open source and privacy-focused',
  ],
  keywords: [
    'keygen',
    'password generator',
    'random key generator',
    'API key generator',
    'UUID generator',
    'JWT secret generator',
    'encryption key generator',
    'secure password generator',
    'random string generator',
    'crypto key generator'
  ],
  mainEntityOfPage: {
    '@type': 'WebPage',
    '@id': 'https://randomkeygen.com',
  },
  potentialAction: {
    '@type': 'UseAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: 'https://randomkeygen.com',
      actionPlatform: ['http://schema.org/DesktopWebPlatform', 'http://schema.org/MobileWebPlatform'],
    },
    object: {
      '@type': 'SoftwareApplication',
      name: 'RandomKeygen Password Generator',
    },
  },
}

// FAQ Schema for common keygen questions
const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'Is RandomKeygen safe to use for generating passwords?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes, RandomKeygen is completely safe. All password and key generation happens locally in your browser using cryptographically secure random number generation. No data is ever sent to our servers or stored anywhere.'
      }
    },
    {
      '@type': 'Question',
      name: 'What types of keys can RandomKeygen generate?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'RandomKeygen can generate secure passwords, passphrases, API keys, JWT secrets, encryption keys (AES, RSA, HMAC), UUIDs, TOTP secrets, framework keys (Django, Laravel, Flask), WiFi passwords, and more.'
      }
    },
    {
      '@type': 'Question',
      name: 'How secure are the passwords generated by RandomKeygen?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'RandomKeygen uses cryptographically secure pseudo-random number generation (CSPRNG) provided by your browser\'s Web Crypto API. This ensures maximum entropy and security for all generated passwords and keys.'
      }
    },
    {
      '@type': 'Question',
      name: 'Can I use RandomKeygen for commercial projects?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes, RandomKeygen is free to use for both personal and commercial projects. The generated keys and passwords can be used in any application or service.'
      }
    },
    {
      '@type': 'Question',
      name: 'Does RandomKeygen work offline?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes, once loaded, RandomKeygen works completely offline. All key generation happens in your browser without requiring any internet connection.'
      }
    }
  ]
}

export default function Home() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <SearchActionSchema searchUrl="https://randomkeygen.com" />
      <HomeClient />
    </>
  )
}
